services:
  db:
    image: postgres:16-alpine
    container_name: tesys-back-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: tesys
      POSTGRES_USER: tesys
      POSTGRES_PASSWORD: tesys
    ports:
      - "5432:5432"
    volumes:
      - tesys-back-db-data:/var/lib/postgresql/data

volumes:
  tesys-back-db-data:
